name: apiverve_cuidgenerator
description: Cuid Generator is a tool for generating collision-resistant unique identifiers (Cuids). Cuids are optimized for horizontal scaling and sequential lookup performance in distributed systems.
version: 1.1.14
homepage: https://apiverve.com/marketplace/cuidgenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/cuidgenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
